services:

  backend:
    build: ./backend
    platform: linux/amd64
    restart: unless-stopped
    environment:
      PORT: 5050
      MONGODB_URI: mongodb+srv://samarthgrover8_db_user:nXCeTe6UldUgRd4d@cluster0.iuz42bz.mongodb.net/?appName=Cluster0
      JWT_SECRET: 6982523gsjgfsegfiwe2r92364623
      JWT_EXPIRES_IN: 7d
      FRONTEND_ORIGIN: http://localhost:4000
      NODE_ENV: production
      SEED_DATABASE: "true"
    volumes:
      - uploads_data:/app/uploads

  frontend:
    build: ./frontend
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "4000:80"
    depends_on:
      - backend

volumes:
  uploads_data:
